### ISSUE TITLE
Error while atempting to lauch project [@Win8.1-64bit]

### ISSUE THREAD

**Issue by dedevillela** [ozasadnyy/zeppelin-grunt#1]
<username>@<computername> MINGW64 ~/documents/github/zeppelin-grunt (master)
$ grunt --force
Running "serve" task

Running "clean:server" (clean) task

> > 0 paths cleaned.

Running "jekyll:server" (jekyll) task
`jekyll build --source app --destination .jekyll/zeppelin-grunt --config _config.yml` was initiated.

Configuration file: _config.yml
jekyll 3.0.0 | Error:  undefined method `read_posts' for class`Jekyll::Site'
Warning:  Used --force, continuing.
Warning: Task "jekyll:server" failed. Used --force, continuing.

Running "copy:server" (copy) task
Created 12 directories, copied 74 files
Loading "sass.js" tasks...ERROR

> > Error: `libsass` bindings not found. Try reinstalling `node-sass`?
> > Warning: Task "sass:server" failed. Used --force, continuing.

Running "autoprefixer:server" (autoprefixer) task

Running "uglify:server" (uglify) task

> > 2 files created.

Running "connect:livereload" (connect) task
Started connect web server on http://localhost:9000

Running "watch" task
Waiting...

**Comment by ozasadnyy** [comment]
@dedevillela it's problem with Jekyll version. try to install the older one

**Comment by dedevillela** [comment]
@ozasadnyy just rolled back to jekyll-2.5.3, but it seems that Bundler did not liked that at all...
$ grunt --force
Running "serve" task

Running "clean:server" (clean) task

> > 0 paths cleaned.

Running "jekyll:server" (jekyll) task

> > Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "jekyll -v"
> > C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find jekyll-3.0.0 in any of the sources (Bundler::GemNotFound)
> >      from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85:in`map!'
> >      from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85:in `materialize'
> >      from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/definition.rb:140:in`specs'
> >      from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/definition.rb:185:in `specs_for'
> >      from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/definition.rb:174:in`requested_specs'
> >      from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/environment.rb:18:in `requested_specs'
> >      from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:13:in`setup'
> >      from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:127:in `setup'
> >      from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:37:in`require_from_bundler'
> >      from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/bin/jekyll:16:in `<top (required)>'
> >      from C:/Ruby22-x64/bin/jekyll:23:in`load'
> >      from C:/Ruby22-x64/bin/jekyll:23:in `<main>'
> > Warning: Please install Jekyll before running this task. Used --force, continuing.
> > Warning: Task "jekyll:server" failed. Used --force, continuing.

Running "copy:server" (copy) task
Created 12 directories, copied 74 files
Loading "sass.js" tasks...ERROR

> > Error: `libsass` bindings not found. Try reinstalling `node-sass`?
> > Warning: Task "sass:server" failed. Used --force, continuing.

Running "autoprefixer:server" (autoprefixer) task

Running "uglify:server" (uglify) task

> > 2 files created.

Running "connect:livereload" (connect) task
Started connect web server on http://localhost:9000

Running "watch" task
Waiting...

**Comment by dedevillela** [comment]
Got it working by forcing jekyll 2.5.3 in Gemfile, still some bumbs here and there, the problem now is JSON and SASS. The project runned in the browser withou a css...

$ grunt --force
Running "serve" task

Running "clean:server" (clean) task

> > 2 paths cleaned.

Running "jekyll:server" (jekyll) task
`jekyll build --source app --destination .jekyll/zeppelin-grunt --config _config.yml` was initiated.

WARN: Unresolved specs during Gem::Specification.reset:
      redcarpet (~> 3.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: _config.yml
            Source: app
       Destination: .jekyll/zeppelin-grunt
      Generating...

Building site for default language: "en" to: C:/Users/dedevillela/documents/github/zeppelin-grunt/.jekyll/zeppelin-grunt
C:/Ruby22-x64/lib/ruby/2.2.0/json/version.rb:3: warning: already initialized constant JSON::VERSION
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/json-1.8.3/lib/json/version.rb:3: warning: previous definition of VERSION was here
C:/Ruby22-x64/lib/ruby/2.2.0/json/version.rb:4: warning: already initialized constant JSON::VERSION_ARRAY
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/json-1.8.3/lib/json/version.rb:4: warning: previous definition of VERSION_ARRAY was here
C:/Ruby22-x64/lib/ruby/2.2.0/json/version.rb:5: warning: already initialized constant JSON::VERSION_MAJOR
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/json-1.8.3/lib/json/version.rb:5: warning: previous definition of VERSION_MAJOR was here
C:/Ruby22-x64/lib/ruby/2.2.0/json/version.rb:6: warning: already initialized constant JSON::VERSION_MINOR
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/json-1.8.3/lib/json/version.rb:6: warning: previous definition of VERSION_MINOR was here
C:/Ruby22-x64/lib/ruby/2.2.0/json/version.rb:7: warning: already initialized constant JSON::VERSION_BUILD
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/json-1.8.3/lib/json/version.rb:7: warning: previous definition of VERSION_BUILD was here
C:/Ruby22-x64/lib/ruby/2.2.0/json/common.rb:99: warning: already initialized constant JSON::NaN
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/json-1.8.3/lib/json/common.rb:99: warning: previous definition of NaN was here
C:/Ruby22-x64/lib/ruby/2.2.0/json/common.rb:101: warning: already initialized constant JSON::Infinity
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/json-1.8.3/lib/json/common.rb:101: warning: previous definition of Infinity was here
C:/Ruby22-x64/lib/ruby/2.2.0/json/common.rb:103: warning: already initialized constant JSON::MinusInfinity
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/json-1.8.3/lib/json/common.rb:103: warning: previous definition of MinusInfinity was here
C:/Ruby22-x64/lib/ruby/2.2.0/json/common.rb:128: warning: already initialized constant JSON::UnparserError
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/json-1.8.3/lib/json/common.rb:128: warning: previous definition of UnparserError was here
Building site for language: "uk" to: C:/Users/dedevillela/documents/github/zeppelin-grunt/.jekyll/zeppelin-grunt/uk
Build complete
                    done.
 Auto-regeneration: disabled. Use --watch to enable.

Running "copy:server" (copy) task
Created 12 directories, copied 74 files
Loading "sass.js" tasks...ERROR

> > Error: `libsass` bindings not found. Try reinstalling `node-sass`?
> > Warning: Task "sass:server" failed. Used --force, continuing.

**Comment by ozasadnyy** [comment]
As you can see you have problem with Sass compilation:

```
Error: libsass bindings not found. Try reinstalling node-sass?
```

Re-run `npm install` and make sure that everything is ok
